### ISSUE TITLE
« export » npm package

### ISSUE THREAD

**Issue by ssirois** [savoirfairelinux/ringme.js#14]
### Expected Behaviour

As a ringme.js user, I want to be able to fetch a npm package at https://www.npmjs.com/package/ringme.js

See https://github.com/savoirfairelinux/ringme.js/pull/10#issuecomment-287803895

### Actual Behaviour

The package is « there », but not exported.

**Comment by ssirois** [comment]
@ventilooo  or @peakwinter any idea if we need to do something in order to _update_ the npm package over npmjs.com ?

Is it _auto-magic_ when there is activity on the master branch?

**Comment by ventilooo** [comment]
@ssirois 
You have to do it manually just like you would publish a docker image.
The npm package is actually under my namespace. I'm gonna maintain the update until we have a savoirfairelinux organization on npmjs.com

Once #16 is done i'm gonna publish the new version as 0.1.2

PS: we need a release incrementation system in order to have clean relase ;)
