### ISSUE TITLE
I'll help

### ISSUE THREAD

**Issue by Sneakykicks** [savoirfairelinux/ringme.js#26]
### Expected Behaviour

Fill me in ...
I'm 11 and I can help you with your project. My current own project is looking pretty stylish so I think I can help.
### Actual Behaviour

Fill me in ...
I'll help you make everything look cute <3
### Steps to reproduce

* step 1
* step 2
* ...

**Comment by ventilooo** [comment]
Great :+1:

**Comment by ssirois** [comment]
@Sneakykicks thank you for your interest.

Please fill free to create a _Pull Request_ proposing your visual already integrated or upload a screenshot with your ideas in a comment on issue #24 

It will be easier to discuss the issue and topics related to it by commenting in a centralized manner on issue #24 

I will therefore close this issue since we do not want to duplicate issues of same topics! Feel free to ask for links to documentation on how to integrate a design on git-pages over there.

Your interest and future contributions if you have time to send ideas and work is appreciated.
