### ISSUE TITLE
Standalone solution

### ISSUE THREAD

**Issue by ssirois** [savoirfairelinux/ringme.js#5]
We should not suggest that it is a good thing to use a CDN (for obvious opacity and privacy reasons).

We should make sure that a Ring user can put a RingMe button on her site without any "call home feature".

**Comment by samnegri** [comment]
Hello @ssirois 

I'm not sure what this issue is about. I understand the problem of distributing it with CDN, do you have any thoughts on how to make the releases available? Won't we publish the releases to npmjs, so anyone can `require()` this project as a dependency, so there is no need to use as a CDN?

**Comment by ssirois** [comment]
@samnegri indeed. This issue was more of a note to self when I first started this little project.

Now that I need to think about it, I think this _issue_ should transform itself in some sort of _text_ in the README file.

I'll create a PR for this.

It is more of a philosophical thing and education thing for users to understand that they should not hit a server they don't control each time one of there page is displayed to a visitor. Or at least, if they do, it must be with _full knowledge_.

It's also a thing to remember the contributors that this projects needs to avoid any _call home_ feature in order for their code to be accepted.

**Comment by samnegri** [comment]
Thank you for the clarification. I read the documentation you added in #40 and I think you made it very clear
